name: check_commit

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "14"
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/checkout@v2

      # - name: Checkout release branch
      #   run: git checkout -b release

      - name: Install
        run: |
          yarn install --frozen-lockfile

      - name: Lint
        run: |
          yarn lint

      - name: Build
        run: |
          yarn build

      - name: Test
        run: |
          yarn test

      - name: Publish
        run: |
          git config --global user.email "bret.maxime@gmail.com"
          git config --global user.name "Maxime Bret"
          npx lerna publish minor --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
