name: check_commit

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "14"
      - uses: actions/checkout@v2

      # - name: Checkout release branch
      #   run: git checkout -b release

      - name: Install
        run: |
          yarn

      - name: Lint
        run: |
          yarn lint

      - name: Build
        run: |
          yarn build

      - name: Test
        run: |
          yarn test

      - name: Publish
        run: |
          npx lerna publish minor --yes
