name: check_publish_lib

on:
  push:
    branches:
      - "master"

jobs:
  check:
    runs-on: macos-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/checkout@v4

      # - name: Checkout release branch
      #   run: git checkout -b release

      - name: Install
        run: |
          npm ci

      # We only build library on this pipe
      - name: Lint
        run: |
          npx lerna run lint --stream --scope @prose-reader/*

      # We only build library on this pipe
      - name: Build
        run: |
          npx lerna run build --stream --scope @prose-reader/*

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Check
        run: |
          npm run tsc

      - name: Test
        run: |
          npm test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: packages/tests/playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: packages/tests/playwright-report/

      - name: Publish
        run: |
          git config --global user.email "bret.maxime@gmail.com"
          git config --global user.name "Maxime Bret"
          npx lerna publish minor --no-private --yes -- --ignore="prose-reader-{demo,front,tests}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
